# Generated by Django 4.2 on 2023-04-26 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/instructor/')),
                ('sports', models.CharField(choices=[('SKI', 'Ski'), ('SNB', 'Snowboard'), ('BTH', 'Both')], default='SKI', max_length=3)),
                ('q_expiration', models.DateField()),
                ('commission', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('picture', models.ImageField(upload_to='img/school/')),
                ('phone', models.CharField(max_length=9)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools_at_address', to='api.address')),
                ('instructors', models.ManyToManyField(related_name='works_for_schools', to='api.instructor')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='languages',
            field=models.ManyToManyField(related_name='instructors_speaking', to='api.language'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='qualifications',
            field=models.ManyToManyField(related_name='instructors_with', to='api.qualification'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sport', models.CharField(choices=[('SKI', 'Ski'), ('SNB', 'Snowboard')], default='SKI', max_length=3)),
                ('num_students', models.IntegerField()),
                ('num_hours', models.IntegerField()),
                ('class_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fees_description', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliable', to='api.instructor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('client_notes', models.TextField()),
                ('instructor_notes', models.TextField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('P', 'Paid'), ('C', 'Cancelled'), ('A', 'Client absent'), ('X', 'Complete')], default='B', max_length=1)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_like_this', to='api.classtype')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_classes', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_classes', to='api.instructor')),
                ('students', models.ManyToManyField(related_name='taking_classes', to='api.student')),
            ],
        ),
    ]
