# Generated by Django 4.2 on 2023-05-15 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='available_end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='classtype',
            name='available_start',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
