# Generated by Django 4.2 on 2023-06-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classtype_available_end_classtype_available_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='commission',
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='instructor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classtype',
            name='fees_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/instructor/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='works_for_schools', to='api.instructor'),
        ),
        migrations.AlterField(
            model_name='school',
            name='picture',
            field=models.ImageField(blank=True, upload_to='img/school/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=9),
        ),
    ]
