openapi: 3.0.3
info:
  title: "API Szkół Narciarskich"
  version: "1.0.0"
  description: "API do zarządzania szkołami narciarskimi oraz instruktorami"
paths:
  /szkoly:
    get:
      summary: "Pobierz listę szkół narciarskich"
      tags:
        - "Szkoly"
      responses:
        200:
          description: "Pomyślnie pobrano listę szkół narciarskich"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Szkola"
    post:
      summary: "Dodaj nową szkołę narciarską"
      tags:
        - "Szkoly"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NowaSzkola"
      responses:
        201:
          description: "Szkola została pomyślnie dodana"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Szkola"
  /szkoly/{id_szkoly}:
    get:
      summary: "Pobierz szczegóły szkoły narciarskiej"
      tags:
        - "Szkoly"
      parameters:
        - name: "id_szkoly"
          in: "path"
          description: "Identyfikator szkoły narciarskiej"
          required: true
          schema:
            type: "integer"
      responses:
        200:
          description: "Pomyślnie pobrano szczegóły szkoły narciarskiej"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Szkola"
    put:
      summary: "Aktualizuj dane szkoły narciarskiej"
      tags:
        - "Szkoly"
      parameters:
        - name: "id_szkoly"
          in: "path"
          description: "Identyfikator szkoły narciarskiej"
          required: true
          schema:
            type: "integer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NowaSzkola"
      responses:
        200:
          description: "Dane szkoły narciarskiej zostały zaktualizowane poprawnie."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Szkola"
    delete:
      summary: "Usuń szkołę narciarską"
      tags:
        - "Szkoly"
      parameters:
        - name: "id_szkoly"
          in: "path"
          description: "Identyfikator szkoły narciarskiej"
          required: true
          schema:
            type: "integer"
      responses:
        204:
          description: "Szkola została usunięta poprawnie."

  /instruktorzy:
    get:
      summary: "Pobierz listę instruktorów"
      tags:
        - "Instruktorzy"
      responses:
        200
